var Queue = require('bull');
var SpotifyWebApi = require('spotify-web-api-node');
var { getPlaylistTracks } = require('../utils/getAll');
var shuffleArray = require('../utils/shuffleArray');

const handlePlaylistShuffle = new Queue('handle-playlist-shuffle');

handlePlaylistShuffle.process(async (job) => {
    const { uri, accessToken } = job.data;
    try {
        const playlistId = uri.split(':')[2];
        const spotifyApi = new SpotifyWebApi({ accessToken: accessToken });

        const res = await spotifyApi.getMe();
        const user = res.body;

        const trackUris = [];
        for await (let playlistTrack of getPlaylistTracks(playlistId, accessToken)) {
            trackUris.push(playlistTrack.track.uri);
        }

        shuffleArray(trackUris);

        const name = `True Shuffle: ${playlistId}`;
        const description = "Generated by Spotify Playlist Manager [www.spotifyplaylistmanager.net]. Turn off Spotify's shuffle and enjoy. :)";
        const newPlaylistRes = await spotifyApi.createPlaylist(name, { public: true, description: description });
        const newPlaylist = newPlaylistRes.body;

        spotifyApi.addTracksToPlaylist(newPlaylist.id, trackUris);
    } catch (err) {
        console.error(err);
    }
});

module.exports = handlePlaylistShuffle;